### ISSUE TITLE
Dynamically Adding Items

### ISSUE THREAD

**Issue by weagertron** [ahmetcanaydemir/react-advanced-news-ticker#4]
I have enjoyed using this library in a couple of projects and think that it's great! Recently I have come across an issue though.
This time around, my use case involves adding items to the news ticker dynamically but I am unsure how to get this to work.

Here is what I have tried [(Sandbox link)](https://codesandbox.io/s/vigilant-boyd-5vmqj?file=/src/App.js:0-551)

```
import React, { useEffect, useState } from "react";
import NewsTicker from "react-advanced-news-ticker";

export default function App() {
  const [items, setItems] = useState([]);

  useEffect(() => {
    setTimeout(() => {
      // simulate API request
      setItems(["Item 1", "Item 2", "Item 3"]);
    }, 3000);
  }, []);

  return (
    <NewsTicker maxRows={1}>
      <div>Hello</div>
      <div>Goodbye</div>
      {items.map((i) => (
        <div key={i}>{i}</div>
      ))}
    </NewsTicker>
  );
}
```

In this example, only the "Hello" and "Goodbye" strings are displayed in the ticker. If I add only the dynamic portions and remove the hard coded "Hello" and "Goodbye" divs, the page refuses to load with an error from the library.

Is there a way I can dynamically add/remove data from the items in the ticker? I have looked through the documentation and cannot find a way of doing it. Apologies if it is something I have overlooked and indeed is documented somewhere.

Thanks.

**Comment by afredericksansait** [comment]
Bumping this as I have the same problem in 2022

**Comment by ahmetcanaydemir** [comment]
I am sorry for the late reply. Unfortunately, I saw it too late. If you want to change the list you must stop the ticker, change items and start the ticker. You can do that by using ref. Here is the fixed version of your sandbox code.

Please look at how I use the `tickerRef.current.start();` part and the `autoStart ` parameter.

If you have any other questions, don't hesitate to ask.

```js
import React, { useEffect, useState, useRef } from "react";
import NewsTicker from "react-advanced-news-ticker";
import "./styles.css";

export default function App() {
  const [items, setItems] = useState(["Hello","Goodbye"]);
  const tickerRef = useRef(null);
  useEffect(() => {
    setTimeout(() => {
      // simulate API request
      setItems(["Hello", "Goodbye", "Item 1", "Item 2", "Item 3"]);
      tickerRef.current.start();
    }, 3000);
  }, []);

  return (
    <NewsTicker
      ref={tickerRef}
      autoStart="false"
      maxRows={1}
      className="noBullets"
    >
      {items.map((item, i) => (
        <div key={i}>{item}</div>
      ))}
    </NewsTicker>
  );
}
```

**Comment by weagertron** [comment]
Thanks @ahmetcanaydemir! I will be sure to try this out. It's always better late than never with this stuff, life is busy. Now this should help anyone else with the issue going forward and we can all enjoy the dynamic items within the ticker 👍
